#!/bin/bash

# Define variables
cpu_info=$(lscpu)
memory_info=$(free -h)
reg_users=$(cut -d: -f1 /etc/passwd)
sudo_users=$(grep -Po '^sudo.+:\K.*$' /etc/group)

display_ver(){
    echo "version v0.1.0"
}

if [ "$1" == "--help" ];
then
    cat /usr/local/bin/internsctl-help
    exit 0
fi

if [ "$1" == "--version" ];
then
    display_ver
    exit 0
fi 

if [ "$1" == "cpu" ] && [ "$2" == "getinfo" ];
then
    echo "$cpu_info"
    exit 0
fi

if [ "$1" == "memory" ] && [ "$2" == "getinfo" ];
then
    echo "$memory_info"
    exit 0
fi

if [ "$1" == "user" ] && [ "$2" == "list" ] && [ "$3" == "--sudo-only" ];
then
    echo "$sudo_users"
    exit 0

elif [ "$1" == "user" ] && [ "$2" == "list" ];
then
    echo "$reg_users"
    exit 0

fi

if [ "$1" == "user" ] && [ "$2" == "create" ] &&  [ -n "$3" ];
then
    sudo useradd -m "$3"
    sudo passwd "$3"
    sudo usermod -s /bin/bash "$3"
    exit 0
fi

