#!/bin/bash

# Define variables
display_ver(){
    echo "version v0.1.0"
}

if [ "$1" == "--help" ];
then
    cat /usr/local/bin/internsctl-help
    exit 0
fi

if [ "$1" == "--version" ];
then
    display_ver
    exit 0
fi 

