#!/bin/bash

# Define variables
cpu_info=$(lscpu)
memory_info=$(free -h)


display_ver(){
    echo "version v0.1.0"
}

if [ "$1" == "--help" ];
then
    cat /usr/local/bin/internsctl-help
    exit 0
fi

if [ "$1" == "--version" ];
then
    display_ver
    exit 0
fi 

if [ "$1" == "cpu" ] && [ "$2" == "getinfo" ];
then
    echo "$cpu_info"
    exit 0
fi

if [ "$1" == "memory" ] && [ "$2" == "getinfo" ];
then
    echo "$memory_info"
    exit 0
fi

